name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    env:
      OPAMROOTISOK: '1'
    strategy:
      matrix:
        os:
          - riscv-builders
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - run: |
              sudo apt update -yq
              sudo apt install -yq opam

      - run: |
             opam init --disable-sandboxing -y
             opam switch -y create 4.14.2
             opam install -y dune

      - run: |
          eval $(opam env)
          dune build -p moonbit-lang

      - run: ./_build/install/default/bin/moonc -v
